// AUTO-GENERATED by the image download script. product id -> local image paths.
export const PRODUCT_IMAGES: Record<string, string[]> = {
  prod_counterfeit_rolex: ["/products/prod_counterfeit_rolex-0.jpg", "/products/prod_counterfeit_rolex-1.jpg", "/products/prod_counterfeit_rolex-2.jpg"],
  prod_viral_honest: ["/products/prod_viral_honest-0.jpg", "/products/prod_viral_honest-1.jpg", "/products/prod_viral_honest-2.jpg", "/products/prod_viral_honest-3.jpg"],
  prod_fabric_kurti: ["/products/prod_fabric_kurti-0.jpg", "/products/prod_fabric_kurti-1.jpg", "/products/prod_fabric_kurti-2.jpg", "/products/prod_fabric_kurti-3.jpg"],
  prod_size_shoes: ["/products/prod_size_shoes-0.jpg", "/products/prod_size_shoes-1.jpg", "/products/prod_size_shoes-2.jpg", "/products/prod_size_shoes-3.jpg"],
  prod_lowrated_fraud: ["/products/prod_lowrated_fraud-0.jpg"],
  prod_fixable_bedsheet: ["/products/prod_fixable_bedsheet-0.jpg", "/products/prod_fixable_bedsheet-1.jpg", "/products/prod_fixable_bedsheet-2.jpg"],
  prod_damaged_courier: ["/products/prod_damaged_courier-0.jpg"],
  prod_knockoff_loved: ["/products/prod_knockoff_loved-0.jpg", "/products/prod_knockoff_loved-1.jpg", "/products/prod_knockoff_loved-2.jpg"],
  prod_normal_mug: ["/products/prod_normal_mug-0.jpg", "/products/prod_normal_mug-1.jpg"],
  prod_normal_notebook: ["/products/prod_normal_notebook-0.jpg", "/products/prod_normal_notebook-1.jpg", "/products/prod_normal_notebook-2.jpg"],
};
