// AUTO-GENERATED. product id -> local image paths.
export const PRODUCT_IMAGES: Record<string, string[]> = {
  prod_counterfeit_rolex: ["/products/prod_counterfeit_rolex-0.jpg", "/products/prod_counterfeit_rolex-1.jpg", "/products/prod_counterfeit_rolex-2.jpg"],
  prod_viral_honest: ["/products/prod_viral_honest-0.jpg", "/products/prod_viral_honest-1.jpg", "/products/prod_viral_honest-2.jpg", "/products/prod_viral_honest-3.jpg"],
  prod_fabric_kurti: ["/products/prod_fabric_kurti-0.jpg", "/products/prod_fabric_kurti-1.jpg", "/products/prod_fabric_kurti-2.jpg", "/products/prod_fabric_kurti-3.jpg"],
  prod_size_shoes: ["/products/prod_size_shoes-0.jpg", "/products/prod_size_shoes-1.jpg", "/products/prod_size_shoes-2.jpg", "/products/prod_size_shoes-3.jpg"],
  prod_lowrated_fraud: ["/products/prod_lowrated_fraud-0.jpg"],
  prod_fixable_bedsheet: ["/products/prod_fixable_bedsheet-0.jpg", "/products/prod_fixable_bedsheet-1.jpg", "/products/prod_fixable_bedsheet-2.jpg"],
  prod_damaged_courier: ["/products/prod_damaged_courier-0.jpg"],
  prod_knockoff_loved: ["/products/prod_knockoff_loved-0.jpg", "/products/prod_knockoff_loved-1.jpg", "/products/prod_knockoff_loved-2.jpg"],
  prod_normal_mug: ["/products/prod_normal_mug-0.jpg", "/products/prod_normal_mug-1.jpg"],
  prod_gadget_powerbank: ["/products/prod_gadget_powerbank-0.jpg"],
  prod_gadget_earphones: ["/products/prod_gadget_earphones-0.jpg"],
  prod_beauty_serum: ["/products/prod_beauty_serum-0.jpg", "/products/prod_beauty_serum-1.jpg", "/products/prod_beauty_serum-2.jpg"],
  prod_beauty_lipstick: ["/products/prod_beauty_lipstick-0.jpg"],
  prod_kids_tshirt: ["/products/prod_kids_tshirt-0.jpg", "/products/prod_kids_tshirt-1.jpg", "/products/prod_kids_tshirt-2.jpg", "/products/prod_kids_tshirt-3.jpg"],
  prod_saree_silk: ["/products/prod_saree_silk-0.jpg", "/products/prod_saree_silk-1.jpg", "/products/prod_saree_silk-2.jpg"],
  prod_mobile_case: ["/products/prod_mobile_case-0.jpg", "/products/prod_mobile_case-1.jpg", "/products/prod_mobile_case-2.jpg", "/products/prod_mobile_case-3.jpg"],
  prod_jewelry_necklace: ["/products/prod_jewelry_necklace-0.jpg", "/products/prod_jewelry_necklace-1.jpg", "/products/prod_jewelry_necklace-2.jpg"],
  prod_scam_watch: ["/products/prod_scam_watch-0.jpg", "/products/prod_scam_watch-1.jpg", "/products/prod_scam_watch-2.jpg"],
  prod_scam_perfume: ["/products/prod_scam_perfume-0.jpg", "/products/prod_scam_perfume-1.jpg", "/products/prod_scam_perfume-2.jpg"],
};
